name: subscriptions cron job
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: check for updates on subscribed addresses and transactions
        run: |
          curl --request GET \
          --url 'https://bitcoin-explorer.vercel.app/api/v1/subscriptions/subscriptionsCronJob'
